
// AUTO GENERATED BY MAGIC (bun run magic build) --- DO NOT EDIT THIS FILE.

export const asset = {
};

export const audioContext = new AudioContext();
export const gain = audioContext.createGain();
gain.connect(audioContext.destination);

var global_volume = 1;

window.magic_setVolume = setVolume;
export function setVolume(volume) {
    global_volume = volume;
    gain.gain.value = volume;
}

window.magic_play = play;

export function play(sound, volume = 1, pitch = 1) {
    var source = audioContext.createBufferSource();
    source.buffer = asset[sound].audio;
    source.connect(audioContext.destination);

    gain.gain.value = volume * global_volume;
    source.playbackRate.value = pitch;

    source.connect(gain);
    source.start();
}

export async function loadAll() {
    const response = await fetch('/assets.bin');
    const arrayBuffer = await response.arrayBuffer();
    var URL = window.URL || window.webkitURL;

    for (let assetName in asset) {
        const data = new Uint8Array(arrayBuffer, asset[assetName].offset, asset[assetName].size);
        const attachedBuffer = new Uint8Array(data).buffer;

        if (asset[assetName].blob === "") {
            const blob = new Blob([data], { type: asset[assetName].type });
            asset[assetName].blob = URL.createObjectURL(blob);
            continue;
        }

        if (asset[assetName].audio === "") {
            asset[assetName].audio = await audioContext.decodeAudioData(attachedBuffer);
            continue;
        }

        if (asset[assetName].data === "") {
            asset[assetName].data = data
            continue;
        }

        if (asset[assetName].text === "") {
            asset[assetName].text = new TextDecoder().decode(attachedBuffer);
        }
    }
}